services:
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - node-express
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  node-express:
    build: node-express
    ports:
      - 3000
    environment:
        NODE_DEV: development
        MONGODB_URL: mongodb://mongodb:27017/node-boilerplate
        JWT_SECRET: thisisasamplesecret
        JWT_ACCESS_EXPIRATION_MINUTES: "30"
        JWT_REFRESH_EXPIRATION_DAYS: "30"
        JWT_RESET_PASSWORD_EXPIRATION_MINUTES: "10"
        JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: "10"
        SMTP_HOST: "email-server"
        SMTP_PORT: "587"
        SMTP_USERNAME: "email-server-username"
        SMTP_PASSWORD: "email-server-password"
        EMAIL_FROM: "support@yourapp.com"
    command: yarn dev
    depends_on:
      - mongodb
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_password
    command: server /data
